sites = [('https://www.bbc.com', 512), ('https://www.jython.org', 847), ('https://www.microsoft.com', 512),
         ('https://www.apple.com', 293), ('http://olympus.realpython.org/dice', 23), ('https://www.facebook.com', 319),
         ('https://www.linkedin.com', 214), ('https://www.microsoft.com', 366), ('https://www.youtube.com', 304),
         ('http://olympus.realpython.org/dice', 242), ('https://www.apple.com', 964), ('https://www.twitter.com', 387),
         ('https://www.bbc.com', 280), ('https://www.nytimes.com', 319), ('https://www.wikipedia.org', 467),
         ('https://www.linkedin.com', 215), ('https://www.twitter.com', 844), ('https://www.bbc.com', 483),
         ('https://www.spotify.com', 681), ('https://www.youtube.com', 662), ('https://www.amazon.com', 659),
         ('https://www.wikipedia.org', 611), ('https://www.spotify.com', 652), ('https://www.twitter.com', 661),
         ('https://www.twitter.com', 823), ('https://www.github.com', 973), ('https://www.amazon.com', 310),
         ('https://www.amazon.com', 788), ('https://www.youtube.com', 619), ('https://www.wikipedia.org', 421),
         ('https://www.airbnb.com', 943), ('https://www.wikipedia.org', 580), ('https://www.airbnb.com', 614),
         ('https://www.microsoft.com', 718), ('https://www.linkedin.com', 939), ('https://www.apple.com', 548),
         ('https://www.facebook.com', 522), ('https://www.instagram.com', 695), ('https://www.youtube.com', 219),
         ('https://www.facebook.com', 739), ('https://www.bbc.com', 614), ('https://www.wikipedia.org', 201),
         ('https://www.bbc.com', 941), ('https://www.stackoverflow.com', 344), ('https://www.netflix.com', 376),
         ('https://www.netflix.com', 686), ('http://olympus.realpython.org/dice', 159),
         ('https://www.netflix.com', 559),
         ('https://www.wikipedia.org', 242), ('https://www.cnn.com', 223), ('https://www.airbnb.com', 362),
         ('https://www.spotify.com', 493), ('https://www.microsoft.com', 672), ('https://www.bbc.com', 500),
         ('https://www.instagram.com', 388), ('https://www.airbnb.com', 607), ('https://www.airbnb.com', 572),
         ('https://www.instagram.com', 538), ('https://www.reddit.com', 349), ('https://www.netflix.com', 786)]
